[project]
name = "semester-thesis"
version = "0.1.0"
description = "python-based project to solve the Traffic Assignment Problem (TAP) using Graph Neural Networks (GNNs)"
requires-python = "~=3.13"
dependencies = [
    "aequilibrae>=1.4.3",
    "dyntapy>=0.2.4",
    "osmnx==1.9.4",
]
